# Generated by Django 4.1.3 on 2023-01-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='topk',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='search',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/upload'),
        ),
    ]
